spring:
  datasource:
    url: jdbc:mysql://mysql-sb-book-social-network:3306/bsndb
    username: admin
    password: abc@#123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ecosystemprogramminglanguage@gmail.com
    password: ainubmlhyfkrbnzy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            trust: "*"

application:
  security:
    jwt:
      secrect-key: E71481A3A9E55CBE78620DD83B5A8FF9ED54107F5DDF47DD4B51756529C474A9
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

  file:
    uploads:
      photos-output-path: ./uploads

cloudinary:
  cloudName: do20urnhr
  apiKey: 923335259698874
  apiSecret: VphL4JPzZYIxEXdAiT8JNyouPuM

server:
  port: 8700
